FROM node:18-bookworm-slim

WORKDIR /app
RUN apt-get update -y && apt-get install -y openssl ca-certificates && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
COPY apps/api/package*.json ./apps/api/
COPY packages ./packages
COPY prisma ./prisma
COPY apps/api ./apps/api
COPY tsconfig.json ./tsconfig.json

RUN npm ci

WORKDIR /app
RUN apt-get update -y && apt-get install -y openssl ca-certificates && rm -rf /var/lib/apt/lists/*
RUN npm run build --workspace=@sewing/api

EXPOSE 3001

ENTRYPOINT ["sh", "/app/apps/api/scripts/docker-entrypoint.sh"]
CMD ["node", "apps/api/dist/main.js"]
